config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length:{ maximum:200 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  validates :name, presence: true, length:{ minimum:2, maximum:20 }, uniqueness: true
  validates :introduction, length: { maximum:50 }

  has_many :books, dependent: :destroy

  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no-image.jpg")
      profile_image.attach(io: File.open(file_path),filename: "default-image.jpg",content_type: "image/jpeg")
    end
    profile_image.variant(resize: size).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book=Book.new
  end

  def create
    @books=Book.all
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :index
    end
  end

  def index
    @book=Book.new
    @books=Book.all
  end

  def show
    @book=Book.new
    @book_show=Book.find(params[:id])
    @user=@book_show.user
  end

  def edit
    @book=Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book=Book.new
    @users=User.all
  end

  def show
    @book=Book.new
    @user=User.find(params[:id])
    @books=@user.books
  end

  def edit
    @user=User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h1>Editing Book</h1>
    <% if @book.errors.any? %>
      <%= @book.errors.count %>error prohibited this obj from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>

    <%= form_with model:@book, method: :patch do |f| %>
        <div class="form-group">
            <h4>title</h4>
            <%= f.text_field :title, class:"form-control" %>
        </div>
        <div class="form-group">
            <h4>Opinion</h4>
            <%= f.text_area :body, class:"form-control" %>
         </div>
        <div class="form-group">
            <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
    <% end %>
    <%= link_to "Show", book_path(@book.id) %>
    |
    <%= link_to "Back", books_path %>
</div>

app/views/books/index.html.erb
<div class=table>
  <%= flash[:notice] %>
</div>

<%= render 'users/info', book: @book, user: current_user %>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr>
          <th>
            <%= link_to user_path(book.user.id) do %>
              <% if book.user.profile_image.attached? %>
                <th><%= image_tag book.user.profile_image, size:"100x100" %></th>
              <% else %>
                <th><%= image_tag 'no-image', size:"100x100" %></th>
              <% end %>
            <% end %>
          </th>
          <th><%= link_to book.title, book_path(book.id) %></th>
          <th><%= book.body %></th>
          <th colspan="3"></th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/show.html.erb
<%= render 'users/info', book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
  	<tbody>
  		  <tr>
  		    <th>
  		      <%= link_to user_path(@user.id) do %>
  		        <%= image_tag @book_show.user.get_profile_image("100x100") %><br>
  		        <%= @user.name %>
  		      <% end %>
          </th>
          <th><%= link_to @book_show.title, book_path(@book_show.id) %></th>
          <th><%= @book_show.body %></th>
          <th>
            <% if @book_show.user == current_user %>
              <%= link_to "Edit", edit_book_path(@book_show.id), class:"btn btn-sm btn-success" %>
            <% end %>
          </th>
          <th>
            <% if @book_show.user == current_user %>
              <%= link_to "Destroy", book_path(@book_show.id), method: :delete, class:"btn btn-sm btn-danger" %>
            <% end %>
          </th>
  		  </tr>
    </tbody>
  </table>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class=row>
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to
        <i class="fas fa-book"></i><strong>Bookers</strong> !!
      </h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
  <h1>welcome to
     <i class="fas fa-book"></i><strong>Bookers</strong> !!
  </h1>
  <p>in <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
  <p>you can share and exchange your opinions , inpressions , and emotions</p>
  <p>about various books!</p>
  <div class="btn-wrapper col-10 mx-auto">
    <div class="row">
      <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
    </div>
    <div class="row">
      <%= link_to "Sign up",new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user), class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i>Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: "nav-link text-light" do %>
                    <i class="fas fa-users"></i>Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: "nav-link text-light" do %>
                    <i class="fas fa-book-open"></i>Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-out-alt"></i>Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i>Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: "nav-link text-light" do %>
                    <i class="fas fa-link"></i>About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                    <i class="fas fa-user-plus"></i>Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt"></i>Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <p id="notice"></p>
        <div class="container">
          <div class=row>
            <%= flash[:notice] %>
            <%= yield %>
          </div>
        </div>
    </main>

    <footer>
      <div class="container mt-5">
  	    <div class="row">
    	    <div class="mx-auto">
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
<div class=table>
  <% if book.errors.any? %>
    <%= book.errors.count %>件のエラーが発生しました
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
</div>

<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag "no-image", size: "100x100" %>
  <table class=table>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </table>

  <div class="row">
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>

  <h2 class="mt-3">New book</h2>
  <%= form_with model:book, method: :post do |f| %>
    <div class="form-group">
      <h4>Title</h4><br>
      <%= f.text_field :title, class:"form-control" %>
    </div>
    <div class="form-group">
      <h4>Body</h4><br>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit"Create Book", class: "btn btn-success" %>
    </div>
  <% end%>
</div>

app/views/users/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <% if @user.errors.any? %>
      <%= @user.errors.count %>error prohibited this obj from being saved:
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>

    <%= form_with model:@user, method: :patch do |f| %>
        <div class="form-group">
            <h4>Name</h4>
            <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
            <h4>Image</h4>
            <%= f.file_field :profile_image,class:"form-control-file" %>
        </div>
        <div class="form-group">
            <h4>Introduction</h4>
            <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
    <% end %>
</div>

app/views/users/index.html.erb
<%= render 'info', book: @book, user: current_user %>
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th>
            <%= link_to user_path(user.id) do %>
              <% if user.profile_image.attached? %>
                <th><%= image_tag user.profile_image, size:"100x100" %></th>
              <% else %>
                <th><%= image_tag 'no-image', size:"100x100" %></th>
              <% end %>
            <% end %></th>
          <th><%= user.name %></th>
          <th><%= link_to "Show", user_path(user.id) %></th>
          <th colspan="3"></th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<%= render 'info', book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr>
          <th>
            <%= link_to user_path(book.user.id) do %>
              <% if book.user.profile_image.attached? %>
                <th><%= image_tag book.user.profile_image, size:"100x100" %></th>
              <% else %>
                <th><%= image_tag 'no-image', size:"100x100" %></th>
              <% end %>
            <% end %>
          </th>
          <th><%= link_to book.title, book_path(book.id) %></th>
          <th><%= book.body%></th>
          <th colspan="3"></th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>